package com.hcl.demo.dataobject;

import java.io.Serializable;
import java.util.List;

import com.hcl.demo.util.DemoConstants;
import com.hcl.demo.util.DemoLogger;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 
public class BaseBO<T> implements Serializable {

	private static final long serialVersionUID = 1L;
	private static final DemoLogger LOGGER = DemoLogger.create(BaseBO.class);

	public T getFirst(List<T> obj, Class<T> clazz) {
		if (obj != null && obj.size() > 0) {
			return obj.get(0);
		} else {
			T o = null;
			try {
				o = clazz.newInstance();
				obj.add(o);//new added 
			} catch (InstantiationException | IllegalAccessException e) {
				LOGGER.error(DemoConstants.ERROR, e);
			}
			return o;
		}
	}
}