package com.hcl.demo.dataobject;

import java.io.Serializable;

import com.hcl.demo.util.DemoUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 
public class E203abenBO extends BaseBO implements Serializable {
	private static final long serialVersionUID = 1L;
	private String wCall = "SPMZABEN";
	private String fillerE203aben1 = "COPYTEXT BE203ABE";
	private Integer e203abenCondcode = 116;
	private String e203abenDumpcode = "N";
	private String fillerE203aben2 = "COPYTEXT BSPMZABE";
	private SpmzabenArea spmzabenArea;
	private Integer linkCondcode;
	private String linkDumpcode;

	public String getWCall() {
		return wCall;

	}

	public void setWCall(String wCall) {
		this.wCall = wCall;
	}

	public String getFillerE203aben1() {
		return fillerE203aben1;

	}

	public void setFillerE203aben1(String fillerE203aben1) {
		this.fillerE203aben1 = fillerE203aben1;
	}

	public Integer getE203abenCondcode() {
		return e203abenCondcode;

	}

	public void setE203abenCondcode(Integer e203abenCondcode) {
		this.e203abenCondcode = e203abenCondcode;
	}

	public String getE203abenCondcodeR() {
		return DemoUtils.readNumberAsString(e203abenCondcode, "0000");

	}

	public void setE203abenCondcodeR(String e203abenCondcodeR) {
		this.e203abenCondcode = DemoUtils.parseToInt(e203abenCondcodeR);
	}

	public String getE203abenDumpcode() {
		return e203abenDumpcode;

	}

	public void setE203abenDumpcode(String e203abenDumpcode) {
		this.e203abenDumpcode = e203abenDumpcode;
	}

	public String getFillerE203aben2() {
		return fillerE203aben2;

	}

	public void setFillerE203aben2(String fillerE203aben2) {
		this.fillerE203aben2 = fillerE203aben2;
	}

	public SpmzabenArea getSpmzabenArea() {
		return spmzabenArea;

	}

	public void setSpmzabenArea(SpmzabenArea spmzabenArea) {
		this.spmzabenArea = spmzabenArea;
	}

	public Integer getLinkCondcode() {
		return linkCondcode;

	}

	public void setLinkCondcode(Integer linkCondcode) {
		this.linkCondcode = linkCondcode;
	}

	public String getLinkDumpcode() {
		return linkDumpcode;

	}

	public void setLinkDumpcode(String linkDumpcode) {
		this.linkDumpcode = linkDumpcode;
	}
}