package com.hcl.demo.dataobject;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 
public class E203abenWrapper extends BaseBO<E203abenBO> implements Serializable {

	private static final long serialVersionUID = 1L;
	private List<E203abenBO> e203abenBO;
	private Integer exeStatus;
	private Integer sqlStatusCode;
	private Map<String, Object> e203abenMap;

	public List<E203abenBO> getE203abenBO() {
		if (e203abenBO == null) {
			e203abenBO = new ArrayList<E203abenBO>();
		}
		return e203abenBO;
	}

	public void setE203abenBO(List<E203abenBO> e203abenBO) {
		this.e203abenBO = e203abenBO;
	}

	public Integer getExeStatus() {
		return exeStatus;
	}

	public void setExeStatus(Integer exeStatus) {
		this.exeStatus = exeStatus;
	}

	public Integer getSqlStatusCode() {
		return sqlStatusCode;
	}

	public void setSqlStatusCode(Integer sqlStatusCode) {
		this.sqlStatusCode = sqlStatusCode;
	}

	public Map<String, Object> getE203abenMap() {
		return e203abenMap;
	}

	public void setE203abenMap(Map<String, Object> e203abenMap) {
		this.e203abenMap = e203abenMap;
	}

	@Override
	public String toString() {
		return "E203abenWrapper [e203abenBO =" + e203abenBO + " ,exeStatus =" + exeStatus + " ,sqlStatusCode =" + sqlStatusCode + " ,e203abenMap =" + e203abenMap + "]";
	}

}