package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class KorAammA extends BaseBO<KorAammA> implements Serializable {
	private static final long serialVersionUID = 1L;

	public KorAammA() {
		super();
	}

	public KorAammA(String data) {
		super();
		setData(data);
	}

	private KorAaA korAaA = new KorAaA();

	private KorMmA korMmA = new KorMmA();

	private KorDdA korDdA = new KorDdA();

	public KorAaA getKorAaA() {
		return korAaA;

	}

	public void setKorAaA(KorAaA korAaA) {
		this.korAaA = korAaA;
	}

	public KorMmA getKorMmA() {
		return korMmA;

	}

	public void setKorMmA(KorMmA korMmA) {
		this.korMmA = korMmA;
	}

	public KorDdA getKorDdA() {
		return korDdA;

	}

	public void setKorDdA(KorDdA korDdA) {
		this.korDdA = korDdA;
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 6);
		this.setKorAaA(new KorAaA(baseData.substring(0, 2)));
		this.setKorMmA(new KorMmA(baseData.substring(2, 6)));
		this.setKorDdA(new KorDdA(baseData.substring(4, 10)));

	}

	@Override
	public String toString() {
		return getKorAaA().toString() + getKorMmA().toString() + getKorDdA().toString();
	}

}