package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

import com.hcl.demo.util.DemoUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class KorDateY extends BaseBO<KorDateY> implements Serializable {
	private static final long serialVersionUID = 1L;

	public KorDateY() {
		super();
	}

	public KorDateY(String data) {
		super();
		if(data.trim().length()>0 && null!=data) {
		setData(data);
		}
	}

	private Integer korSs;

	private KorDate korDate = new KorDate();

	public Integer getKorSs() {
		return korSs;

	}

	public void setKorSs(Integer korSs) {
		this.korSs = korSs;
	}

	public KorDate getKorDate() {
		return korDate;

	}

	public void setKorDate(KorDate korDate) {
		this.korDate = korDate;
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 6);
		this.setKorSs((Integer) DemoUtils.readFieldAsNumber(baseData.substring(0, 2), "##", Integer.class));
		this.setKorDate(new KorDate(baseData.substring(2, 8)));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getKorSs().toString(), 2) + getKorDate().toString();
	}

}