package com.hcl.demo.dataobject;

import java.io.Serializable;
import java.math.BigDecimal;

import org.apache.commons.lang3.StringUtils;

import com.hcl.demo.util.DemoUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class KorlogWrite extends BaseBO<KorlogWrite> implements Serializable {
	private static final long serialVersionUID = 1L;

	public KorlogWrite() {
		super();
	}

	public KorlogWrite(String data) {
		super();
		setData(data);
	}

	private String antalWrite = "ANTAL SKRIVNA RADER               ";

	private BigDecimal klSiffror2 = new BigDecimal("0");

	private String fillerKorlogWrite1 = " ";

	public String getAntalWrite() {
		return antalWrite;

	}

	public void setAntalWrite(String antalWrite) {
		this.antalWrite = antalWrite;
	}

	public BigDecimal getKlSiffror2() {
		return klSiffror2;

	}

	public void setKlSiffror2(BigDecimal klSiffror2) {
		this.klSiffror2 = klSiffror2;
	}

	public String getFillerKorlogWrite1() {
		return fillerKorlogWrite1;

	}

	public void setFillerKorlogWrite1(String fillerKorlogWrite1) {
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 70);
		this.setAntalWrite(baseData.substring(0, 35));
		this.setKlSiffror2((BigDecimal) DemoUtils.readFieldAsNumber(baseData.substring(35, 42), "#######", BigDecimal.class));
		this.setFillerKorlogWrite1(baseData.substring(42, 70));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getAntalWrite().toString(), 35) + StringUtils.rightPad(getKlSiffror2().toString(), 7) + StringUtils.rightPad(getFillerKorlogWrite1().toString(), 28);
	}

}