package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

import com.hcl.demo.util.DemoUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class MaskAammddA extends BaseBO<MaskAammddA> implements Serializable {
	private static final long serialVersionUID = 1L;

	public MaskAammddA() {
		super();
	}

	public MaskAammddA(String data) {
		super();
		setData(data);
	}

	private Integer maskAammdd;

	public Integer getMaskAammdd() {
		return maskAammdd;

	}

	public void setMaskAammdd(Integer maskAammdd) {
		this.maskAammdd = maskAammdd;
	}

	public void setData(String baseData) {
		//baseData="200709";
		baseData = StringUtils.rightPad(baseData, 6);
		this.setMaskAammdd((Integer) DemoUtils.readFieldAsNumber(baseData.substring(0, 6), "######", Integer.class));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getMaskAammdd().toString(), 6);
	}

}