package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

import com.hcl.demo.util.DemoUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class SpmzabenArea extends BaseBO<SpmzabenArea> implements Serializable {
	private static final long serialVersionUID = 1L;

	public SpmzabenArea() {
		super();
	}

	public SpmzabenArea(String data) {
		super();
		setData(data);
	}

	private Integer spmzabenReturkod;

	private String spmzabenDumpcode;

	private String spmzabenHuvudpgm;

	private String spmzabenFeltext;

	public Integer getSpmzabenReturkod() {
		return spmzabenReturkod;

	}

	public void setSpmzabenReturkod(Integer spmzabenReturkod) {
		this.spmzabenReturkod = spmzabenReturkod;
	}

	public String getSpmzabenDumpcode() {
		return spmzabenDumpcode;

	}

	public void setSpmzabenDumpcode(String spmzabenDumpcode) {
		this.spmzabenDumpcode = spmzabenDumpcode;
	}

	public String getSpmzabenHuvudpgm() {
		return spmzabenHuvudpgm;

	}

	public void setSpmzabenHuvudpgm(String spmzabenHuvudpgm) {
		this.spmzabenHuvudpgm = spmzabenHuvudpgm;
	}

	public String getSpmzabenFeltext() {
		return spmzabenFeltext;

	}

	public void setSpmzabenFeltext(String spmzabenFeltext) {
		this.spmzabenFeltext = spmzabenFeltext;
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 27);
		this.setSpmzabenReturkod((Integer) DemoUtils.readFieldAsNumber(baseData.substring(0, 3), "####", Integer.class));
		this.setSpmzabenDumpcode(baseData.substring(3, 4));
		this.setSpmzabenHuvudpgm(baseData.substring(4, 12));
		this.setSpmzabenFeltext(baseData.substring(12, 27));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getSpmzabenReturkod().toString(), 3) + StringUtils.rightPad(getSpmzabenDumpcode().toString(), 1) + StringUtils.rightPad(getSpmzabenHuvudpgm().toString(), 8) + StringUtils.rightPad(getSpmzabenFeltext().toString(), 15);
	}

}