package com.hcl.demo.dataobject;

import java.io.Serializable;
import java.math.BigInteger;

import org.apache.commons.lang3.StringUtils;

import com.hcl.demo.util.DemoUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class UtCvpmv05 extends BaseBO<UtCvpmv05> implements Serializable {
	private static final long serialVersionUID = 1L;

	public UtCvpmv05() {
		super();
	}

	public UtCvpmv05(String data) {
		super();
		setData(data);
	}

	private BigInteger utCvpmv05Sqlkod;

	public BigInteger getUtCvpmv05Sqlkod() {
		return utCvpmv05Sqlkod;

	}

	public void setUtCvpmv05Sqlkod(BigInteger utCvpmv05Sqlkod) {
		this.utCvpmv05Sqlkod = utCvpmv05Sqlkod;
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 9);
		this.setUtCvpmv05Sqlkod((BigInteger) DemoUtils.readFieldAsNumber(baseData.substring(0, 9), "#########", BigInteger.class));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getUtCvpmv05Sqlkod().toString(), 9);
	}

}