package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class UtKAbend8 extends BaseBO<UtKAbend8> implements Serializable {
	private static final long serialVersionUID = 1L;

	public UtKAbend8() {
		super();
	}

	public UtKAbend8(String data) {
		super();
		setData(data);
	}

	private String fillerUtKAbend81 = " ";

	private String fillerUtKAbend82 = "****** VPBV05  A B E N D  RAPPORT SLUT  ***";

	public String getFillerUtKAbend81() {
		return fillerUtKAbend81;

	}

	public void setFillerUtKAbend81(String fillerUtKAbend81) {
	}

	public String getFillerUtKAbend82() {
		return fillerUtKAbend82;

	}

	public void setFillerUtKAbend82(String fillerUtKAbend82) {
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 60);
		this.setFillerUtKAbend81(baseData.substring(0, 1));
		this.setFillerUtKAbend82(baseData.substring(1, 60));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getFillerUtKAbend81().toString(), 1) + StringUtils.rightPad(getFillerUtKAbend82().toString(), 59);
	}

}