package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

import com.hcl.demo.util.DemoUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class UtKAbend7 extends BaseBO<UtKAbend7> implements Serializable {
	private static final long serialVersionUID = 1L;

	public UtKAbend7() {
		super();
	}

	public UtKAbend7(String data) {
		super();
		setData(data);
	}

	private String fillerUtKAbend71 = " ";

	private String utKAStatustext = " ";

	private Integer utKAStatus = 0;

	public String getFillerUtKAbend71() {
		return fillerUtKAbend71;

	}

	public void setFillerUtKAbend71(String fillerUtKAbend71) {
	}

	public String getUtKAStatustext() {
		return utKAStatustext;

	}

	public void setUtKAStatustext(String utKAStatustext) {
		this.utKAStatustext = utKAStatustext;
	}

	public Integer getUtKAStatus() {
		return utKAStatus;

	}

	public void setUtKAStatus(Integer utKAStatus) {
		this.utKAStatus = utKAStatus;
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 22);
		this.setFillerUtKAbend71(baseData.substring(0, 1));
		this.setUtKAStatustext(baseData.substring(1, 21));
		this.setUtKAStatus((Integer) DemoUtils.readFieldAsNumber(baseData.substring(21, 22), "#", Integer.class));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getFillerUtKAbend71().toString(), 1) + StringUtils.rightPad(getUtKAStatustext().toString(), 20) + StringUtils.rightPad(getUtKAStatus().toString(), 1);
	}

}