package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class UtKAbend2 extends BaseBO<UtKAbend2> implements Serializable {
	private static final long serialVersionUID = 1L;

	public UtKAbend2() {
		super();
	}

	public UtKAbend2(String data) {
		super();
		setData(data);
	}

	private String fillerUtKAbend21 = " ";

	private String utKAVy = " ";

	private String fillerUtKAbend22 = "ANROP : ";

	private String utKAAnrop = " ";

	public String getFillerUtKAbend21() {
		return fillerUtKAbend21;

	}

	public void setFillerUtKAbend21(String fillerUtKAbend21) {
	}

	public String getUtKAVy() {
		return utKAVy;

	}

	public void setUtKAVy(String utKAVy) {
		this.utKAVy = utKAVy;
	}

	public String getFillerUtKAbend22() {
		return fillerUtKAbend22;

	}

	public void setFillerUtKAbend22(String fillerUtKAbend22) {
	}

	public String getUtKAAnrop() {
		return utKAAnrop;

	}

	public void setUtKAAnrop(String utKAAnrop) {
		this.utKAAnrop = utKAAnrop;
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 60);
		this.setFillerUtKAbend21(baseData.substring(0, 1));
		this.setUtKAVy(baseData.substring(1, 11));
		this.setFillerUtKAbend22(baseData.substring(11, 19));
		this.setUtKAAnrop(baseData.substring(19, 60));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getFillerUtKAbend21().toString(), 1) + StringUtils.rightPad(getUtKAVy().toString(), 10) + StringUtils.rightPad(getFillerUtKAbend22().toString(), 8) + StringUtils.rightPad(getUtKAAnrop().toString(), 41);
	}

}