package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class UtKAbend6 extends BaseBO<UtKAbend6> implements Serializable {
	private static final long serialVersionUID = 1L;

	public UtKAbend6() {
		super();
	}

	public UtKAbend6(String data) {
		super();
		setData(data);
	}

	private String fillerUtKAbend61 = " ";

	private String utKAOvrigt = " ";

	public String getFillerUtKAbend61() {
		return fillerUtKAbend61;

	}

	public void setFillerUtKAbend61(String fillerUtKAbend61) {
	}

	public String getUtKAOvrigt() {
		return utKAOvrigt;

	}

	public void setUtKAOvrigt(String utKAOvrigt) {
		this.utKAOvrigt = utKAOvrigt;
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 60);
		this.setFillerUtKAbend61(baseData.substring(0, 1));
		this.setUtKAOvrigt(baseData.substring(1, 60));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getFillerUtKAbend61().toString(), 1) + StringUtils.rightPad(getUtKAOvrigt().toString(), 59);
	}

}