package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class UtKAbend1 extends BaseBO<UtKAbend1> implements Serializable {
	private static final long serialVersionUID = 1L;

	public UtKAbend1() {
		super();
	}

	public UtKAbend1(String data) {
		super();
		setData(data);
	}

	private String fillerUtKAbend11 = " ";

	private String fillerUtKAbend12 = "****** VPBV05  A B E N D  R A P P O R T ***";

	public String getFillerUtKAbend11() {
		return fillerUtKAbend11;

	}

	public void setFillerUtKAbend11(String fillerUtKAbend11) {
	}

	public String getFillerUtKAbend12() {
		return fillerUtKAbend12;

	}

	public void setFillerUtKAbend12(String fillerUtKAbend12) {
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 60);
		this.setFillerUtKAbend11(baseData.substring(0, 1));
		this.setFillerUtKAbend12(baseData.substring(1, 60));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getFillerUtKAbend11().toString(), 1) + StringUtils.rightPad(getFillerUtKAbend12().toString(), 59);
	}

}