package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class UtKBlank extends BaseBO<UtKBlank> implements Serializable {
	private static final long serialVersionUID = 1L;

	public UtKBlank() {
		super();
	}

	public UtKBlank(String data) {
		super();
		setData(data);
	}

	private String fillerUtKBlank1 = " ";

	private String fillerUtKBlank2 = " ";

	public String getFillerUtKBlank1() {
		return fillerUtKBlank1;

	}

	public void setFillerUtKBlank1(String fillerUtKBlank1) {
	}

	public String getFillerUtKBlank2() {
		return fillerUtKBlank2;

	}

	public void setFillerUtKBlank2(String fillerUtKBlank2) {
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 60);
		this.setFillerUtKBlank1(baseData.substring(0, 1));
		this.setFillerUtKBlank2(baseData.substring(1, 60));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getFillerUtKBlank1().toString(), 1) + StringUtils.rightPad(getFillerUtKBlank2().toString(), 59);
	}

}