package com.hcl.demo.dataobject;

import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 

public class UtKJStart extends BaseBO<UtKJStart> implements Serializable {
	private static final long serialVersionUID = 1L;

	public UtKJStart() {
		super();
	}

	public UtKJStart(String data) {
		super();
		setData(data);
	}

	private String fillerUtKJStart1 = "";

	private String fillerUtKJStart2 = "****** VPBV05  K O R L O G G  BORJAN ******";

	public String getFillerUtKJStart1() {
		return fillerUtKJStart1;

	}

	public void setFillerUtKJStart1(String fillerUtKJStart1) {
	}

	public String getFillerUtKJStart2() {
		return fillerUtKJStart2;

	}

	public void setFillerUtKJStart2(String fillerUtKJStart2) {
	}

	public void setData(String baseData) {
		baseData = StringUtils.rightPad(baseData, 60);
		this.setFillerUtKJStart1(baseData.substring(0, 1));
		this.setFillerUtKJStart2(baseData.substring(1, 60));

	}

	@Override
	public String toString() {
		return StringUtils.rightPad(getFillerUtKJStart1().toString(), 1) + StringUtils.rightPad(getFillerUtKJStart2().toString(), 59);
	}

}