package com.hcl.demo.dataobject;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.Serializable;

import org.apache.commons.lang3.StringUtils;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hcl.demo.io.SequentialFileReader;
import com.hcl.demo.io.SequentialFileWriter;
import com.hcl.demo.util.DemoUtils;

/**
 * **********************************************************************
 *
 *  HCL CONFIDENTIAL
 *  _________________________________________________________________________________
 *
 *  HCL is a trademark of HCL Company.
 *
 *  Copyright © 2020 HCL. All rights reserved.
 *
 *  NOTICE: All information contained herein is, and remains the property of HCL
 *  and its suppliers, if any. The intellectual and technical concepts contained
 *  herein are proprietary to HCL and its suppliers and may be covered by U.S.
 *  and Foreign Patents, patents in process, and are protected by trade secret or
 *  copyright law. Dissemination of this information or reproduction of this
 *  material is strictly forbidden unless prior written permission is obtained
 *  from HCL.
 *
 * ***********************************************************************
 */
// Author : Generated by ATMA ®
// Revision History :
public class Vpbv05BO extends BaseBO implements Serializable {

	private static final long serialVersionUID = 1L;
    
	@JsonIgnore
	private SequentialFileReader sequentialFileReaderInfil;
	@JsonIgnore
	private SequentialFileWriter sequentialFileWriterInfil;

	private String infilPost;

	@JsonIgnore
	private SequentialFileReader sequentialFileReaderKoerlog;
	@JsonIgnore
	private SequentialFileWriter sequentialFileWriterKoerlog;

	private KoerlogPost koerlogPost;

	private Integer indSlutInfil = 0;

	private static final Integer SLUTINFIL = 1;

	private UtKAbend1 utKAbend1;

	private UtKAbend2 utKAbend2;

	private UtKAbend3 utKAbend3;

	private UtKAbend6 utKAbend6;

	private UtKAbend7 utKAbend7;

	private UtKAbend8 utKAbend8;

	private UtKBlank utKBlank;

	private UtKJStart utKJStart;

	private UtKJSlut utKJSlut;

	private UtKDatum1 utKDatum1;

	private String wsOvrigAbendtext;

	private Arbetsareor arbetsareor;

	private KorlogRead korlogRead;

	private KorlogWrite korlogWrite;

	private InCvpmv05 inCvpmv05;

	private UtCvpmv05 utCvpmv05;

	private Integer e203abenCondcode = 116;

	private String e203abenDumpcode = "N";

	private BnewdateKortY bnewdateKortY;

	private BnewdateKortYRed bnewdateKortYRed;

	private String korDatumRed;

	private FillerVpbv051 fillerVpbv051;

	private KorDateY korDateY;

	private FillerVpbv052 fillerVpbv052;

	private FillerVpbv053 fillerVpbv053;

	private FillerVpbv054 fillerVpbv054;

	private String maskDatumRed;

	private FillerVpbv055 fillerVpbv055;

	private MaskDateY maskDateY;

	private FillerVpbv056 fillerVpbv056;

	public SequentialFileReader getSequentialFileReaderInfil() {
		return sequentialFileReaderInfil;
	}

	public void setSequentialFileReaderInfil(SequentialFileReader sequentialFileReaderInfil) {
		this.sequentialFileReaderInfil = sequentialFileReaderInfil;
	}

	public SequentialFileWriter getSequentialFileWriterInfil() {
		return sequentialFileWriterInfil;
	}

	public void setSequentialFileWriterInfil(SequentialFileWriter sequentialFileWriterInfil) {
		this.sequentialFileWriterInfil = sequentialFileWriterInfil;
	}

	public String getInfilPost() {
		return infilPost;
	}

	public void setInfilPost(String infilPost) {
		this.infilPost = infilPost;
	}

	public SequentialFileReader getSequentialFileReaderKoerlog() {
			return sequentialFileReaderKoerlog;
	}

	public void setSequentialFileReaderKoerlog(SequentialFileReader sequentialFileReaderKoerlog) {
		this.sequentialFileReaderKoerlog = sequentialFileReaderKoerlog;
	}

	public SequentialFileWriter getSequentialFileWriterKoerlog() {
		if (null == sequentialFileWriterKoerlog) {
			try {
				
				File LogFile = new File ("skrivKoerlog.txt");
				LogFile.createNewFile();		
				
				
				sequentialFileWriterKoerlog = new SequentialFileWriter(LogFile.getName());
				//sequentialFileWriterKoerlog = new SequentialFileWriter("skrivKoerlog.txt");
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		return sequentialFileWriterKoerlog;
	}


	public void setSequentialFileWriterKoerlog(SequentialFileWriter sequentialFileWriterKoerlog) {
		this.sequentialFileWriterKoerlog = sequentialFileWriterKoerlog;
	}

	public KoerlogPost getKoerlogPost() {
		return koerlogPost;
	}

	public void setKoerlogPost(KoerlogPost koerlogPost) {
		this.koerlogPost = koerlogPost;
	}

	public Integer getIndSlutInfil() {
		return indSlutInfil;
	}

	public void setIndSlutInfil(Integer indSlutInfil) {
		this.indSlutInfil = indSlutInfil;
	}

	public boolean isSlutInfil() {
		return SLUTINFIL == indSlutInfil;
	}

	public void setAsSlutInfil() {
		this.indSlutInfil = SLUTINFIL;
	}

	public UtKAbend1 getUtKAbend1() {
		return utKAbend1;
	}

	public void setUtKAbend1(UtKAbend1 utKAbend1) {
		this.utKAbend1 = utKAbend1;
	}

	public UtKAbend2 getUtKAbend2() {
		return utKAbend2;
	}

	public void setUtKAbend2(UtKAbend2 utKAbend2) {
		this.utKAbend2 = utKAbend2;
	}

	public UtKAbend3 getUtKAbend3() {
		return utKAbend3;
	}

	public void setUtKAbend3(UtKAbend3 utKAbend3) {
		this.utKAbend3 = utKAbend3;
	}

	public UtKAbend6 getUtKAbend6() {
		return utKAbend6;
	}

	public void setUtKAbend6(UtKAbend6 utKAbend6) {
		this.utKAbend6 = utKAbend6;
	}

	public UtKAbend7 getUtKAbend7() {
		return utKAbend7;
	}

	public void setUtKAbend7(UtKAbend7 utKAbend7) {
		this.utKAbend7 = utKAbend7;
	}

	public UtKAbend8 getUtKAbend8() {
		return utKAbend8;
	}

	public void setUtKAbend8(UtKAbend8 utKAbend8) {
		this.utKAbend8 = utKAbend8;
	}

	public UtKBlank getUtKBlank() {
		return utKBlank;
	}

	public void setUtKBlank(UtKBlank utKBlank) {
		this.utKBlank = utKBlank;
	}

	public UtKJStart getUtKJStart() {
		return utKJStart;
	}

	public void setUtKJStart(UtKJStart utKJStart) {
		this.utKJStart = utKJStart;
	}

	public UtKJSlut getUtKJSlut() {
		return utKJSlut;
	}

	public void setUtKJSlut(UtKJSlut utKJSlut) {
		this.utKJSlut = utKJSlut;
	}

	public UtKDatum1 getUtKDatum1() {
		return utKDatum1;
	}

	public void setUtKDatum1(UtKDatum1 utKDatum1) {
		this.utKDatum1 = utKDatum1;
	}

	public String getWsOvrigAbendtext() {
		return wsOvrigAbendtext;
	}

	public void setWsOvrigAbendtext(String wsOvrigAbendtext) {
		this.wsOvrigAbendtext = wsOvrigAbendtext;
	}

	public Arbetsareor getArbetsareor() {
		return arbetsareor;
	}

	public void setArbetsareor(Arbetsareor arbetsareor) {
		this.arbetsareor = arbetsareor;
	}

	public KorlogRead getKorlogRead() {
		
		if(null==korlogRead) {
			korlogRead = new KorlogRead();
		}
		return korlogRead;
	}

	public void setKorlogRead(KorlogRead korlogRead) {
		this.korlogRead = korlogRead;
	}

	public KorlogWrite getKorlogWrite() {
		return korlogWrite;
	}

	public void setKorlogWrite(KorlogWrite korlogWrite) {
		this.korlogWrite = korlogWrite;
	}

	public InCvpmv05 getInCvpmv05() {
		return inCvpmv05;
	}

	public void setInCvpmv05(InCvpmv05 inCvpmv05) {
		this.inCvpmv05 = inCvpmv05;
	}

	public UtCvpmv05 getUtCvpmv05() {
		return utCvpmv05;
	}

	public void setUtCvpmv05(UtCvpmv05 utCvpmv05) {
		this.utCvpmv05 = utCvpmv05;
	}

	public Integer getE203abenCondcode() {
		return e203abenCondcode;
	}

	public void setE203abenCondcode(Integer e203abenCondcode) {
		this.e203abenCondcode = e203abenCondcode;
	}

	public String getE203abenDumpcode() {
		return e203abenDumpcode;
	}

	public void setE203abenDumpcode(String e203abenDumpcode) {
		this.e203abenDumpcode = e203abenDumpcode;
	}

	public BnewdateKortY getBnewdateKortY() {
		return bnewdateKortY;
	}

	public void setBnewdateKortY(BnewdateKortY bnewdateKortY) {
		this.bnewdateKortY = bnewdateKortY;
	}

	public BnewdateKortYRed getBnewdateKortYRed() {
		return bnewdateKortYRed;
	}

	public void setBnewdateKortYRed(BnewdateKortYRed bnewdateKortYRed) {
		this.bnewdateKortY.setData(bnewdateKortYRed.toString());
	}

	public String getKorDatumRed() {
		return korDatumRed;
	}

	public void setKorDatumRed(String korDatumRed) {
		this.korDatumRed = korDatumRed;
	}

	public FillerVpbv051 getFillerVpbv051() {
		return fillerVpbv051;
	}

	public void setFillerVpbv051(FillerVpbv051 fillerVpbv051) {
		this.korDatumRed = fillerVpbv051.toString();
	}

	public KorDateY getKorDateY() {
		return korDateY;
	}

	public void setKorDateY(KorDateY korDateY) {
		this.korDateY = korDateY;
	}

	public FillerVpbv052 getFillerVpbv052() {
		return fillerVpbv052;
	}

	public void setFillerVpbv052(FillerVpbv052 fillerVpbv052) {
		this.korDateY.setData(fillerVpbv052.toString());
	}

	public FillerVpbv053 getFillerVpbv053() {
		return fillerVpbv053;
	}

	public void setFillerVpbv053(FillerVpbv053 fillerVpbv053) {
		this.korDateY.setData(fillerVpbv053.toString());
	}

	public FillerVpbv054 getFillerVpbv054() {
		return fillerVpbv054;
	}

	public void setFillerVpbv054(FillerVpbv054 fillerVpbv054) {
		this.korDateY.setData(fillerVpbv054.toString());
	}

	public String getMaskDatumRed() {
		return maskDatumRed;
	}

	public void setMaskDatumRed(String maskDatumRed) {
		this.maskDatumRed = maskDatumRed;
	}

	public FillerVpbv055 getFillerVpbv055() {
		return fillerVpbv055;
	}

	public void setFillerVpbv055(FillerVpbv055 fillerVpbv055) {
		this.maskDatumRed = fillerVpbv055.toString();
	}

	public MaskDateY getMaskDateY() {
		return maskDateY;
	}

	public void setMaskDateY(MaskDateY maskDateY) {
		this.maskDateY = maskDateY;
	}

	public FillerVpbv056 getFillerVpbv056() {
		return fillerVpbv056;
	}

	public void setFillerVpbv056(FillerVpbv056 fillerVpbv056) {
		this.maskDateY.setData(fillerVpbv056.toString());
	}

	public class FillerVpbv056 extends BaseBO<FillerVpbv056> {

		public MaskSsaammddA getMaskSsaammddA() {
			String baseData = getMaskDateY().toString();
			return new MaskSsaammddA(baseData.substring(0, 8));
		}

		public void setMaskSsaammddA(MaskSsaammddA maskSsaammddA) {
			String baseData = getMaskDateY().toString();
			baseData = StringUtils.rightPad(baseData, 1213);
			baseData = StringUtils.overlay(baseData, maskSsaammddA.toString(), 0, 8);
			getMaskDateY().setData(baseData);
		}

		public void setData(String baseData) {
			baseData = StringUtils.rightPad(baseData, 1213);
		}

		/*
		 * @Override public String toString() { return getMaskDateY().toString(); }
		 */
	}

	public class FillerVpbv055 extends BaseBO<FillerVpbv055> {

		public String getFillerFillerVpbv0551() {
			String baseData = getMaskDatumRed().toString();
			return StringUtils.rightPad(baseData, 10).substring(0, 4);
		}

		public void setFillerFillerVpbv0551(String fillerFillerVpbv0551) {
			setMaskDatumRed(StringUtils.rightPad(getMaskDatumRed(), 10));
			String maskDatumRedAsString = getMaskDatumRed().toString();
			setMaskDatumRed(StringUtils.overlay(maskDatumRedAsString, fillerFillerVpbv0551.toString(), 0, 4));
		}

		public String getMaskDatumRed01Streck() {
			String baseData = getMaskDatumRed().toString();
			return StringUtils.rightPad(baseData, 10).substring(4, 5);
		}

		public void setMaskDatumRed01Streck(String maskDatumRed01Streck) {
			setMaskDatumRed(StringUtils.rightPad(getMaskDatumRed(), 10));
			String maskDatumRedAsString = getMaskDatumRed().toString();
			setMaskDatumRed(StringUtils.overlay(maskDatumRedAsString, maskDatumRed01Streck.toString(), 4, 5));
		}

		public String getFillerFillerVpbv0552() {
			String baseData = getMaskDatumRed().toString();
			return StringUtils.rightPad(baseData, 10).substring(5, 7);
		}

		public void setFillerFillerVpbv0552(String fillerFillerVpbv0552) {
			setMaskDatumRed(StringUtils.rightPad(getMaskDatumRed(), 10));
			String maskDatumRedAsString = getMaskDatumRed().toString();
			setMaskDatumRed(StringUtils.overlay(maskDatumRedAsString, fillerFillerVpbv0552.toString(), 5, 7));
		}

		public String getMaskDatumRed02Streck() {
			String baseData = getMaskDatumRed().toString();
			return StringUtils.rightPad(baseData, 10).substring(7, 8);
		}

		public void setMaskDatumRed02Streck(String maskDatumRed02Streck) {
			setMaskDatumRed(StringUtils.rightPad(getMaskDatumRed(), 10));
			String maskDatumRedAsString = getMaskDatumRed().toString();
			setMaskDatumRed(StringUtils.overlay(maskDatumRedAsString, maskDatumRed02Streck.toString(), 7, 8));
		}

		public String getFillerFillerVpbv0553() {
			String baseData = getMaskDatumRed().toString();
			return StringUtils.rightPad(baseData, 10).substring(8, 10);
		}

		public void setFillerFillerVpbv0553(String fillerFillerVpbv0553) {
			setMaskDatumRed(StringUtils.rightPad(getMaskDatumRed(), 10));
			String maskDatumRedAsString = getMaskDatumRed().toString();
			setMaskDatumRed(StringUtils.overlay(maskDatumRedAsString, fillerFillerVpbv0553.toString(), 8, 10));
		}

		public void setData(String baseData) {
			baseData = StringUtils.rightPad(baseData, 10);
		}

		@Override
		public String toString() {
			return getMaskDatumRed().toString();
		}
	}

	public class FillerVpbv054 extends BaseBO<FillerVpbv054> {

		public KorSsaammddA getKorSsaammddA() {
			String baseData = getKorDateY().toString();
			return new KorSsaammddA(baseData.substring(0, 8));
		}

		public void setKorSsaammddA(KorSsaammddA korSsaammddA) {
			String baseData = getKorDateY().toString();
			baseData = StringUtils.rightPad(baseData, 1195);
			baseData = StringUtils.overlay(baseData, korSsaammddA.toString(), 0, 8);
			getKorDateY().setData(baseData);
		}

		public void setData(String baseData) {
			baseData = StringUtils.rightPad(baseData, 1195);
		}

		@Override
		public String toString() {
			return getKorDateY().toString();
		}
	}

	public class FillerVpbv053 extends BaseBO<FillerVpbv053> {

		public KorSsaammA getKorSsaammA() {
			String baseData = getKorDateY().toString();
			return new KorSsaammA(baseData.substring(0, 6));
		}

		public void setKorSsaammA(KorSsaammA korSsaammA) {
			String baseData = getKorDateY().toString();
			baseData = StringUtils.rightPad(baseData, 1195);
			baseData = StringUtils.overlay(baseData, korSsaammA.toString(), 0, 6);
			getKorDateY().setData(baseData);
		}

		public Integer getFillerFillerVpbv0531() {
			String baseData = getKorDateY().toString();
			return DemoUtils.parseToInt(baseData.substring(6, 8));
		}

		public void setFillerFillerVpbv0531(Integer fillerFillerVpbv0531) {
			String baseData = getKorDateY().toString();
			baseData = StringUtils.rightPad(baseData, 1195);
			baseData = StringUtils.overlay(baseData, fillerFillerVpbv0531.toString(), 6, 8);
			getKorDateY().setData(baseData);
		}

		public void setData(String baseData) {
			baseData = StringUtils.rightPad(baseData, 1195);
		}

		@Override
		public String toString() {
			return getKorDateY().toString();
		}
	}

	public class FillerVpbv052 extends BaseBO<FillerVpbv052> {

		public KorSsaaA getKorSsaaA() {
			String baseData = getKorDateY().toString();
			return new KorSsaaA(baseData.substring(0, 4));
		}

		public void setKorSsaaA(KorSsaaA korSsaaA) {
			String baseData = getKorDateY().toString();
			baseData = StringUtils.rightPad(baseData, 1195);
			baseData = StringUtils.overlay(baseData, korSsaaA.toString(), 0, 4);
			getKorDateY().setData(baseData);
		}

		public Integer getFillerFillerVpbv0521() {
			String baseData = getKorDateY().toString();
			return DemoUtils.parseToInt(baseData.substring(4, 8));
		}

		public void setFillerFillerVpbv0521(Integer fillerFillerVpbv0521) {
			String baseData = getKorDateY().toString();
			baseData = StringUtils.rightPad(baseData, 1195);
			baseData = StringUtils.overlay(baseData, fillerFillerVpbv0521.toString(), 4, 8);
			getKorDateY().setData(baseData);
		}

		public void setData(String baseData) {
			baseData = StringUtils.rightPad(baseData, 1195);
		}

		@Override
		public String toString() {
			return getKorDateY().toString();
		}
	}

	public class FillerVpbv051 extends BaseBO<FillerVpbv051> {

		public String getFillerFillerVpbv0511() {
			String baseData = getKorDatumRed().toString();
			return StringUtils.rightPad(baseData, 10).substring(0, 4);
		}

		public void setFillerFillerVpbv0511(String fillerFillerVpbv0511) {
			setKorDatumRed(StringUtils.rightPad(getKorDatumRed(), 10));
			String korDatumRedAsString = getKorDatumRed().toString();
			setKorDatumRed(StringUtils.overlay(korDatumRedAsString, fillerFillerVpbv0511.toString(), 0, 4));
		}

		public String getKorDatumRed01Streck() {
			String baseData = getKorDatumRed().toString();
			return StringUtils.rightPad(baseData, 10).substring(4, 5);
		}

		public void setKorDatumRed01Streck(String korDatumRed01Streck) {
			setKorDatumRed(StringUtils.rightPad(getKorDatumRed(), 10));
			String korDatumRedAsString = getKorDatumRed().toString();
			setKorDatumRed(StringUtils.overlay(korDatumRedAsString, korDatumRed01Streck.toString(), 4, 5));
		}

		public String getFillerFillerVpbv0512() {
			String baseData = getKorDatumRed().toString();
			return StringUtils.rightPad(baseData, 10).substring(5, 7);
		}

		public void setFillerFillerVpbv0512(String fillerFillerVpbv0512) {
			setKorDatumRed(StringUtils.rightPad(getKorDatumRed(), 10));
			String korDatumRedAsString = getKorDatumRed().toString();
			setKorDatumRed(StringUtils.overlay(korDatumRedAsString, fillerFillerVpbv0512.toString(), 5, 7));
		}

		public String getKorDatumRed02Streck() {
			String baseData = getKorDatumRed().toString();
			return StringUtils.rightPad(baseData, 10).substring(7, 8);
		}

		public void setKorDatumRed02Streck(String korDatumRed02Streck) {
			setKorDatumRed(StringUtils.rightPad(getKorDatumRed(), 10));
			String korDatumRedAsString = getKorDatumRed().toString();
			setKorDatumRed(StringUtils.overlay(korDatumRedAsString, korDatumRed02Streck.toString(), 7, 8));
		}

		public String getFillerFillerVpbv0513() {
			String baseData = getKorDatumRed().toString();
			return StringUtils.rightPad(baseData, 10).substring(8, 10);
		}

		public void setFillerFillerVpbv0513(String fillerFillerVpbv0513) {
			setKorDatumRed(StringUtils.rightPad(getKorDatumRed(), 10));
			String korDatumRedAsString = getKorDatumRed().toString();
			setKorDatumRed(StringUtils.overlay(korDatumRedAsString, fillerFillerVpbv0513.toString(), 8, 10));
		}

		public void setData(String baseData) {
			baseData = StringUtils.rightPad(baseData, 10);
		}

		@Override
		public String toString() {
			return getKorDatumRed().toString();
		}
	}

	public class BnewdateKortYRed extends BaseBO<BnewdateKortYRed> {

		public NewdSsaammddA getNewdSsaammddA() {
			String baseData = getBnewdateKortY().toString();
			return new NewdSsaammddA(baseData.substring(0, 8));
		}

		public void setNewdSsaammddA(NewdSsaammddA newdSsaammddA) {
			String baseData = getBnewdateKortY().toString();
			baseData = StringUtils.rightPad(baseData, 1177);
			baseData = StringUtils.overlay(baseData, newdSsaammddA.toString(), 0, 8);
			getBnewdateKortY().setData(baseData);
		}

		public String getFillerBnewdateKortYRed1() {
			String baseData = getBnewdateKortY().toString();
			return baseData.substring(8, 80);
		}

		public void setFillerBnewdateKortYRed1(String fillerBnewdateKortYRed1) {
			String baseData = getBnewdateKortY().toString();
			baseData = StringUtils.rightPad(baseData, 1177);
			baseData = StringUtils.overlay(baseData, fillerBnewdateKortYRed1.toString(), 8, 80);
			getBnewdateKortY().setData(baseData);
		}

		public void setData(String baseData) {
			baseData = StringUtils.rightPad(baseData, 1177);
		}

		@Override
		public String toString() {
			return getBnewdateKortY().toString();
		}
		
	
	}
}
