package com.hcl.demo.dataobject;

import java.io.Serializable;

/*************************************************************************
 * 
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 * 
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 * 
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History : 
public class Vpmv05BO extends BaseBO implements Serializable {
	private static final long serialVersionUID = 1L;
	private String fillerVpmv051 = "START W-S SECTION ";
	private String wsLage = "VPMV05";
	private Tvvpsku tvvpsku;
	private Sqlareor sqlareor;
	private InCvpmv05 inCvpmv05;
	private UtCvpmv05 utCvpmv05;

	public String getFillerVpmv051() {
		return fillerVpmv051;

	}

	public void setFillerVpmv051(String fillerVpmv051) {
		this.fillerVpmv051 = fillerVpmv051;
	}

	public String getWsLage() {
		return wsLage;

	}

	public void setWsLage(String wsLage) {
		this.wsLage = wsLage;
	}

	public Tvvpsku getTvvpsku() {
		return tvvpsku;

	}

	public void setTvvpsku(Tvvpsku tvvpsku) {
		this.tvvpsku = tvvpsku;
	}

	public Sqlareor getSqlareor() {
		return sqlareor;

	}

	public void setSqlareor(Sqlareor sqlareor) {
		this.sqlareor = sqlareor;
	}

	public InCvpmv05 getInCvpmv05() {
		return inCvpmv05;

	}

	public void setInCvpmv05(InCvpmv05 inCvpmv05) {
		this.inCvpmv05 = inCvpmv05;
	}

	public UtCvpmv05 getUtCvpmv05() {
		return utCvpmv05;

	}

	public void setUtCvpmv05(UtCvpmv05 utCvpmv05) {
		this.utCvpmv05 = utCvpmv05;
	}
}