package com.hcl.demo.repositories;

import java.util.List;

import com.hcl.demo.dataobject.Vpmv05Wrapper;
import com.hcl.demo.exception.DemoDataAccessException;
import com.hcl.demo.util.DemoLogger;
import com.hcl.demo.util.DemoConstants;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :

public interface IVpmv05Repository {


    public Vpmv05Wrapper insertTvvpsku0(Vpmv05Wrapper vpmv05Wrapper) throws DemoDataAccessException;

    public Vpmv05Wrapper updateTvvpsku1(Vpmv05Wrapper vpmv05Wrapper) throws DemoDataAccessException;

}