package com.hcl.demo.util;

import java.time.format.DateTimeFormatter;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public  class DemoConstants {

    public static final String REQUEST = "Entry into the method";
    public static final String ERROR = "Error in the method";
    public static final String RESPONSE = "Exit from the method";
    public static final String PERSISTENCEUNITNAME = "DemoConstants";
    public static final int SQLNORECORDCODE = 100;
    public static final int SQLSUCCESSCODE = 0;
    public static final int SQLERRORCODE = 999;
    public static final int SQLSTATE = 803;
    public static final DateTimeFormatter DATETIMEFORMATTER = DateTimeFormatter.ofPattern("MM/dd/yyyy 'at' hh:mm a z");
    public static final DateTimeFormatter DATEFORMATTER = DateTimeFormatter.ofPattern("MM/dd/yyyy");
    public static final DateTimeFormatter FOMATTER = DateTimeFormatter.ofPattern("hh:mm a");


}