package com.hcl.demo.exception;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public  class DemoBusinessException extends Exception {

    private static final long serialVersionUID = 2288096558361439469L;

    public DemoBusinessException(Throwable ex) {
        super(ex);
    }

    public DemoBusinessException(String message, Throwable cause) {
        super(message, cause);
    }

    public DemoBusinessException(String message) {
        super(message);
    }
}