package com.hcl.demo.exception;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2020 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public  class DemoDataAccessException extends Exception {

    private static final long serialVersionUID = 2287096558361439469L;

    private final String errorCode;

    private int SQLErrorCode;

    public  DemoDataAccessException(Throwable ex) {
        super(ex);
        this.errorCode = "";
    }

    public  DemoDataAccessException(Throwable ex, int SQLErrorCode) {
        super(ex);
        this.errorCode = "";
        this.SQLErrorCode = SQLErrorCode;
    }

    public  DemoDataAccessException(String message, Throwable cause) {
        super(message, cause);
        this.errorCode = "";
    }

    public  DemoDataAccessException(String message) {
        super(message);
        this.errorCode = "";
    }

    public  DemoDataAccessException(Throwable ex, String errorCode) {
        super(ex);
        this.errorCode = errorCode;
    }

    public  DemoDataAccessException(String message, Throwable cause, String errorCode) {
        super(message, cause);
        this.errorCode = errorCode;
    }

    public  DemoDataAccessException(String message, String errorCode) {
        super(message);
        this.errorCode = errorCode;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public int getSQLErrorCode() {
        return SQLErrorCode;
    }

}